version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mi_proyecto_postgres
    environment:
      - POSTGRES_DB=bd_mente_abierta
      - POSTGRES_USER=usuario_admin
      - POSTGRES_PASSWORD=mi_clave_secreta
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: